// ============================================================
// lib/banks.ts — Nigerian bank codes (Flutterwave-compatible)
// ============================================================
import type { NigerianBank } from '@/types';

export const NIGERIAN_BANKS: NigerianBank[] = [
  { code: '044', name: 'Access Bank' },
  { code: '063', name: 'Access Bank (Diamond)' },
  { code: '035A', name: 'ALAT by WEMA' },
  { code: '401', name: 'ASO Savings and Loans' },
  { code: '023', name: 'Citibank Nigeria' },
  { code: '050', name: 'Ecobank Nigeria' },
  { code: '562', name: 'Ekondo Microfinance Bank' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '214', name: 'First City Monument Bank' },
  { code: '058', name: 'Guaranty Trust Bank' },
  { code: '030', name: 'Heritage Bank' },
  { code: '301', name: 'Jaiz Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '527', name: 'Kuda Bank' },
  { code: '526', name: 'Moniepoint Microfinance Bank' },
  { code: '076', name: 'Polaris Bank' },
  { code: '101', name: 'ProvidusBank' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '100', name: 'Suntrust Bank' },
  { code: '032', name: 'Union Bank of Nigeria' },
  { code: '033', name: 'United Bank For Africa' },
  { code: '215', name: 'Unity Bank' },
  { code: '035', name: 'Wema Bank' },
  { code: '057', name: 'Zenith Bank' },
  { code: '120001', name: 'Opay' },
  { code: '100004', name: 'Palmpay' },
];

/** Format a number as Nigerian Naira */
export function formatNGN(amount: number): string {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 2,
  }).format(amount);
}

/** Convert probability price (0–1) to percentage display */
export function priceToPercent(price: number): string {
  return `${(price * 100).toFixed(0)}%`;
}

/** Generate a unique transaction reference containing the user ID */
export function generateTxRef(userId: string): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8).toUpperCase();
  // Format: NP-{userId}-{timestamp}-{random}
  // The userId is extracted back in the webhook handler
  return `NP-${userId}-${timestamp}-${random}`;
}

/** Extract userId from a tx_ref generated by generateTxRef */
export function extractUserIdFromTxRef(txRef: string): string | null {
  const parts = txRef.split('-');
  // Format: NP-{userId}-{timestamp}-{random}
  // UUID has 5 parts separated by hyphens, so total parts = 1 + 5 + 1 + 1 = 8
  if (parts.length < 8 || parts[0] !== 'NP') return null;
  // Rejoin UUID parts (indices 1–5)
  return parts.slice(1, 6).join('-');
}

/** Validate 10-digit Nigerian bank account number */
export function isValidNUBAN(account: string): boolean {
  return /^\d{10}$/.test(account);
}

/** Generate a unique withdrawal reference */
export function generateWithdrawalRef(withdrawalId: string): string {
  return `NP-WD-${withdrawalId}-${Date.now()}`;
}
